/*
Torizon OTA

 This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  

API version: 2.0-Beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SimpleDeviceNotAffectedInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimpleDeviceNotAffectedInfo{}

// SimpleDeviceNotAffectedInfo struct for SimpleDeviceNotAffectedInfo
type SimpleDeviceNotAffectedInfo struct {
	DeviceUuid string `json:"deviceUuid"`
	DeviceId string `json:"deviceId"`
	Name string `json:"name"`
	EcuErrors map[string]ErrorRepresentation `json:"ecuErrors"`
}

type _SimpleDeviceNotAffectedInfo SimpleDeviceNotAffectedInfo

// NewSimpleDeviceNotAffectedInfo instantiates a new SimpleDeviceNotAffectedInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimpleDeviceNotAffectedInfo(deviceUuid string, deviceId string, name string, ecuErrors map[string]ErrorRepresentation) *SimpleDeviceNotAffectedInfo {
	this := SimpleDeviceNotAffectedInfo{}
	this.DeviceUuid = deviceUuid
	this.DeviceId = deviceId
	this.Name = name
	this.EcuErrors = ecuErrors
	return &this
}

// NewSimpleDeviceNotAffectedInfoWithDefaults instantiates a new SimpleDeviceNotAffectedInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimpleDeviceNotAffectedInfoWithDefaults() *SimpleDeviceNotAffectedInfo {
	this := SimpleDeviceNotAffectedInfo{}
	return &this
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *SimpleDeviceNotAffectedInfo) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *SimpleDeviceNotAffectedInfo) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *SimpleDeviceNotAffectedInfo) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetDeviceId returns the DeviceId field value
func (o *SimpleDeviceNotAffectedInfo) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *SimpleDeviceNotAffectedInfo) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *SimpleDeviceNotAffectedInfo) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetName returns the Name field value
func (o *SimpleDeviceNotAffectedInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SimpleDeviceNotAffectedInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SimpleDeviceNotAffectedInfo) SetName(v string) {
	o.Name = v
}

// GetEcuErrors returns the EcuErrors field value
func (o *SimpleDeviceNotAffectedInfo) GetEcuErrors() map[string]ErrorRepresentation {
	if o == nil {
		var ret map[string]ErrorRepresentation
		return ret
	}

	return o.EcuErrors
}

// GetEcuErrorsOk returns a tuple with the EcuErrors field value
// and a boolean to check if the value has been set.
func (o *SimpleDeviceNotAffectedInfo) GetEcuErrorsOk() (*map[string]ErrorRepresentation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcuErrors, true
}

// SetEcuErrors sets field value
func (o *SimpleDeviceNotAffectedInfo) SetEcuErrors(v map[string]ErrorRepresentation) {
	o.EcuErrors = v
}

func (o SimpleDeviceNotAffectedInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimpleDeviceNotAffectedInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deviceUuid"] = o.DeviceUuid
	toSerialize["deviceId"] = o.DeviceId
	toSerialize["name"] = o.Name
	toSerialize["ecuErrors"] = o.EcuErrors
	return toSerialize, nil
}

func (o *SimpleDeviceNotAffectedInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deviceUuid",
		"deviceId",
		"name",
		"ecuErrors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSimpleDeviceNotAffectedInfo := _SimpleDeviceNotAffectedInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSimpleDeviceNotAffectedInfo)

	if err != nil {
		return err
	}

	*o = SimpleDeviceNotAffectedInfo(varSimpleDeviceNotAffectedInfo)

	return err
}

type NullableSimpleDeviceNotAffectedInfo struct {
	value *SimpleDeviceNotAffectedInfo
	isSet bool
}

func (v NullableSimpleDeviceNotAffectedInfo) Get() *SimpleDeviceNotAffectedInfo {
	return v.value
}

func (v *NullableSimpleDeviceNotAffectedInfo) Set(val *SimpleDeviceNotAffectedInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSimpleDeviceNotAffectedInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSimpleDeviceNotAffectedInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimpleDeviceNotAffectedInfo(val *SimpleDeviceNotAffectedInfo) *NullableSimpleDeviceNotAffectedInfo {
	return &NullableSimpleDeviceNotAffectedInfo{value: val, isSet: true}
}

func (v NullableSimpleDeviceNotAffectedInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimpleDeviceNotAffectedInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


