/*
Torizon OTA

 This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  

API version: 2.0-Beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworkInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkInfo{}

// NetworkInfo struct for NetworkInfo
type NetworkInfo struct {
	DeviceUuid string `json:"deviceUuid"`
	LocalIpV4 *string `json:"localIpV4,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	MacAddress *string `json:"macAddress,omitempty"`
}

type _NetworkInfo NetworkInfo

// NewNetworkInfo instantiates a new NetworkInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkInfo(deviceUuid string) *NetworkInfo {
	this := NetworkInfo{}
	this.DeviceUuid = deviceUuid
	return &this
}

// NewNetworkInfoWithDefaults instantiates a new NetworkInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkInfoWithDefaults() *NetworkInfo {
	this := NetworkInfo{}
	return &this
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *NetworkInfo) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *NetworkInfo) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *NetworkInfo) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetLocalIpV4 returns the LocalIpV4 field value if set, zero value otherwise.
func (o *NetworkInfo) GetLocalIpV4() string {
	if o == nil || IsNil(o.LocalIpV4) {
		var ret string
		return ret
	}
	return *o.LocalIpV4
}

// GetLocalIpV4Ok returns a tuple with the LocalIpV4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInfo) GetLocalIpV4Ok() (*string, bool) {
	if o == nil || IsNil(o.LocalIpV4) {
		return nil, false
	}
	return o.LocalIpV4, true
}

// HasLocalIpV4 returns a boolean if a field has been set.
func (o *NetworkInfo) HasLocalIpV4() bool {
	if o != nil && !IsNil(o.LocalIpV4) {
		return true
	}

	return false
}

// SetLocalIpV4 gets a reference to the given string and assigns it to the LocalIpV4 field.
func (o *NetworkInfo) SetLocalIpV4(v string) {
	o.LocalIpV4 = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *NetworkInfo) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInfo) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *NetworkInfo) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *NetworkInfo) SetHostname(v string) {
	o.Hostname = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *NetworkInfo) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInfo) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *NetworkInfo) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *NetworkInfo) SetMacAddress(v string) {
	o.MacAddress = &v
}

func (o NetworkInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deviceUuid"] = o.DeviceUuid
	if !IsNil(o.LocalIpV4) {
		toSerialize["localIpV4"] = o.LocalIpV4
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	return toSerialize, nil
}

func (o *NetworkInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deviceUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkInfo := _NetworkInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkInfo)

	if err != nil {
		return err
	}

	*o = NetworkInfo(varNetworkInfo)

	return err
}

type NullableNetworkInfo struct {
	value *NetworkInfo
	isSet bool
}

func (v NullableNetworkInfo) Get() *NetworkInfo {
	return v.value
}

func (v *NullableNetworkInfo) Set(val *NetworkInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkInfo(val *NetworkInfo) *NullableNetworkInfo {
	return &NullableNetworkInfo{value: val, isSet: true}
}

func (v NullableNetworkInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


