/*
Torizon OTA

 This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  

API version: 2.0-Beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the DelegationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DelegationInfo{}

// DelegationInfo struct for DelegationInfo
type DelegationInfo struct {
	LastFetched NullableTime `json:"lastFetched,omitempty"`
	RemoteUri NullableString `json:"remoteUri,omitempty"`
	FriendlyName NullableString `json:"friendlyName,omitempty"`
}

// NewDelegationInfo instantiates a new DelegationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelegationInfo() *DelegationInfo {
	this := DelegationInfo{}
	return &this
}

// NewDelegationInfoWithDefaults instantiates a new DelegationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDelegationInfoWithDefaults() *DelegationInfo {
	this := DelegationInfo{}
	return &this
}

// GetLastFetched returns the LastFetched field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DelegationInfo) GetLastFetched() time.Time {
	if o == nil || IsNil(o.LastFetched.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastFetched.Get()
}

// GetLastFetchedOk returns a tuple with the LastFetched field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DelegationInfo) GetLastFetchedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastFetched.Get(), o.LastFetched.IsSet()
}

// HasLastFetched returns a boolean if a field has been set.
func (o *DelegationInfo) HasLastFetched() bool {
	if o != nil && o.LastFetched.IsSet() {
		return true
	}

	return false
}

// SetLastFetched gets a reference to the given NullableTime and assigns it to the LastFetched field.
func (o *DelegationInfo) SetLastFetched(v time.Time) {
	o.LastFetched.Set(&v)
}
// SetLastFetchedNil sets the value for LastFetched to be an explicit nil
func (o *DelegationInfo) SetLastFetchedNil() {
	o.LastFetched.Set(nil)
}

// UnsetLastFetched ensures that no value is present for LastFetched, not even an explicit nil
func (o *DelegationInfo) UnsetLastFetched() {
	o.LastFetched.Unset()
}

// GetRemoteUri returns the RemoteUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DelegationInfo) GetRemoteUri() string {
	if o == nil || IsNil(o.RemoteUri.Get()) {
		var ret string
		return ret
	}
	return *o.RemoteUri.Get()
}

// GetRemoteUriOk returns a tuple with the RemoteUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DelegationInfo) GetRemoteUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteUri.Get(), o.RemoteUri.IsSet()
}

// HasRemoteUri returns a boolean if a field has been set.
func (o *DelegationInfo) HasRemoteUri() bool {
	if o != nil && o.RemoteUri.IsSet() {
		return true
	}

	return false
}

// SetRemoteUri gets a reference to the given NullableString and assigns it to the RemoteUri field.
func (o *DelegationInfo) SetRemoteUri(v string) {
	o.RemoteUri.Set(&v)
}
// SetRemoteUriNil sets the value for RemoteUri to be an explicit nil
func (o *DelegationInfo) SetRemoteUriNil() {
	o.RemoteUri.Set(nil)
}

// UnsetRemoteUri ensures that no value is present for RemoteUri, not even an explicit nil
func (o *DelegationInfo) UnsetRemoteUri() {
	o.RemoteUri.Unset()
}

// GetFriendlyName returns the FriendlyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DelegationInfo) GetFriendlyName() string {
	if o == nil || IsNil(o.FriendlyName.Get()) {
		var ret string
		return ret
	}
	return *o.FriendlyName.Get()
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DelegationInfo) GetFriendlyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FriendlyName.Get(), o.FriendlyName.IsSet()
}

// HasFriendlyName returns a boolean if a field has been set.
func (o *DelegationInfo) HasFriendlyName() bool {
	if o != nil && o.FriendlyName.IsSet() {
		return true
	}

	return false
}

// SetFriendlyName gets a reference to the given NullableString and assigns it to the FriendlyName field.
func (o *DelegationInfo) SetFriendlyName(v string) {
	o.FriendlyName.Set(&v)
}
// SetFriendlyNameNil sets the value for FriendlyName to be an explicit nil
func (o *DelegationInfo) SetFriendlyNameNil() {
	o.FriendlyName.Set(nil)
}

// UnsetFriendlyName ensures that no value is present for FriendlyName, not even an explicit nil
func (o *DelegationInfo) UnsetFriendlyName() {
	o.FriendlyName.Unset()
}

func (o DelegationInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DelegationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.LastFetched.IsSet() {
		toSerialize["lastFetched"] = o.LastFetched.Get()
	}
	if o.RemoteUri.IsSet() {
		toSerialize["remoteUri"] = o.RemoteUri.Get()
	}
	if o.FriendlyName.IsSet() {
		toSerialize["friendlyName"] = o.FriendlyName.Get()
	}
	return toSerialize, nil
}

type NullableDelegationInfo struct {
	value *DelegationInfo
	isSet bool
}

func (v NullableDelegationInfo) Get() *DelegationInfo {
	return v.value
}

func (v *NullableDelegationInfo) Set(val *DelegationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDelegationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDelegationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelegationInfo(val *DelegationInfo) *NullableDelegationInfo {
	return &NullableDelegationInfo{value: val, isSet: true}
}

func (v NullableDelegationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelegationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


