/*
Torizon OTA

 This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  

API version: 2.0-Beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Package type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Package{}

// Package struct for Package
type Package struct {
	Name string `json:"name"`
	Version string `json:"version"`
	PackageId string `json:"packageId"`
	Size int64 `json:"size"`
	Hashes map[string]string `json:"hashes"`
	PkgType NullableString `json:"pkgType,omitempty"`
	HardwareIds []string `json:"hardwareIds,omitempty"`
	CreatedAt NullableTime `json:"createdAt,omitempty"`
	Uri NullableString `json:"uri,omitempty"`
	ProprietaryMeta NullableString `json:"proprietaryMeta,omitempty"`
	Comment NullableString `json:"comment,omitempty"`
}

type _Package Package

// NewPackage instantiates a new Package object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackage(name string, version string, packageId string, size int64, hashes map[string]string) *Package {
	this := Package{}
	this.Name = name
	this.Version = version
	this.PackageId = packageId
	this.Size = size
	this.Hashes = hashes
	return &this
}

// NewPackageWithDefaults instantiates a new Package object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageWithDefaults() *Package {
	this := Package{}
	return &this
}

// GetName returns the Name field value
func (o *Package) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Package) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Package) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *Package) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Package) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Package) SetVersion(v string) {
	o.Version = v
}

// GetPackageId returns the PackageId field value
func (o *Package) GetPackageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value
// and a boolean to check if the value has been set.
func (o *Package) GetPackageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PackageId, true
}

// SetPackageId sets field value
func (o *Package) SetPackageId(v string) {
	o.PackageId = v
}

// GetSize returns the Size field value
func (o *Package) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *Package) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *Package) SetSize(v int64) {
	o.Size = v
}

// GetHashes returns the Hashes field value
func (o *Package) GetHashes() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Hashes
}

// GetHashesOk returns a tuple with the Hashes field value
// and a boolean to check if the value has been set.
func (o *Package) GetHashesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hashes, true
}

// SetHashes sets field value
func (o *Package) SetHashes(v map[string]string) {
	o.Hashes = v
}

// GetPkgType returns the PkgType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Package) GetPkgType() string {
	if o == nil || IsNil(o.PkgType.Get()) {
		var ret string
		return ret
	}
	return *o.PkgType.Get()
}

// GetPkgTypeOk returns a tuple with the PkgType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetPkgTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkgType.Get(), o.PkgType.IsSet()
}

// HasPkgType returns a boolean if a field has been set.
func (o *Package) HasPkgType() bool {
	if o != nil && o.PkgType.IsSet() {
		return true
	}

	return false
}

// SetPkgType gets a reference to the given NullableString and assigns it to the PkgType field.
func (o *Package) SetPkgType(v string) {
	o.PkgType.Set(&v)
}
// SetPkgTypeNil sets the value for PkgType to be an explicit nil
func (o *Package) SetPkgTypeNil() {
	o.PkgType.Set(nil)
}

// UnsetPkgType ensures that no value is present for PkgType, not even an explicit nil
func (o *Package) UnsetPkgType() {
	o.PkgType.Unset()
}

// GetHardwareIds returns the HardwareIds field value if set, zero value otherwise.
func (o *Package) GetHardwareIds() []string {
	if o == nil || IsNil(o.HardwareIds) {
		var ret []string
		return ret
	}
	return o.HardwareIds
}

// GetHardwareIdsOk returns a tuple with the HardwareIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetHardwareIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.HardwareIds) {
		return nil, false
	}
	return o.HardwareIds, true
}

// HasHardwareIds returns a boolean if a field has been set.
func (o *Package) HasHardwareIds() bool {
	if o != nil && !IsNil(o.HardwareIds) {
		return true
	}

	return false
}

// SetHardwareIds gets a reference to the given []string and assigns it to the HardwareIds field.
func (o *Package) SetHardwareIds(v []string) {
	o.HardwareIds = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Package) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Package) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *Package) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *Package) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *Package) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetUri returns the Uri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Package) GetUri() string {
	if o == nil || IsNil(o.Uri.Get()) {
		var ret string
		return ret
	}
	return *o.Uri.Get()
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uri.Get(), o.Uri.IsSet()
}

// HasUri returns a boolean if a field has been set.
func (o *Package) HasUri() bool {
	if o != nil && o.Uri.IsSet() {
		return true
	}

	return false
}

// SetUri gets a reference to the given NullableString and assigns it to the Uri field.
func (o *Package) SetUri(v string) {
	o.Uri.Set(&v)
}
// SetUriNil sets the value for Uri to be an explicit nil
func (o *Package) SetUriNil() {
	o.Uri.Set(nil)
}

// UnsetUri ensures that no value is present for Uri, not even an explicit nil
func (o *Package) UnsetUri() {
	o.Uri.Unset()
}

// GetProprietaryMeta returns the ProprietaryMeta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Package) GetProprietaryMeta() string {
	if o == nil || IsNil(o.ProprietaryMeta.Get()) {
		var ret string
		return ret
	}
	return *o.ProprietaryMeta.Get()
}

// GetProprietaryMetaOk returns a tuple with the ProprietaryMeta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetProprietaryMetaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProprietaryMeta.Get(), o.ProprietaryMeta.IsSet()
}

// HasProprietaryMeta returns a boolean if a field has been set.
func (o *Package) HasProprietaryMeta() bool {
	if o != nil && o.ProprietaryMeta.IsSet() {
		return true
	}

	return false
}

// SetProprietaryMeta gets a reference to the given NullableString and assigns it to the ProprietaryMeta field.
func (o *Package) SetProprietaryMeta(v string) {
	o.ProprietaryMeta.Set(&v)
}
// SetProprietaryMetaNil sets the value for ProprietaryMeta to be an explicit nil
func (o *Package) SetProprietaryMetaNil() {
	o.ProprietaryMeta.Set(nil)
}

// UnsetProprietaryMeta ensures that no value is present for ProprietaryMeta, not even an explicit nil
func (o *Package) UnsetProprietaryMeta() {
	o.ProprietaryMeta.Unset()
}

// GetComment returns the Comment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Package) GetComment() string {
	if o == nil || IsNil(o.Comment.Get()) {
		var ret string
		return ret
	}
	return *o.Comment.Get()
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Comment.Get(), o.Comment.IsSet()
}

// HasComment returns a boolean if a field has been set.
func (o *Package) HasComment() bool {
	if o != nil && o.Comment.IsSet() {
		return true
	}

	return false
}

// SetComment gets a reference to the given NullableString and assigns it to the Comment field.
func (o *Package) SetComment(v string) {
	o.Comment.Set(&v)
}
// SetCommentNil sets the value for Comment to be an explicit nil
func (o *Package) SetCommentNil() {
	o.Comment.Set(nil)
}

// UnsetComment ensures that no value is present for Comment, not even an explicit nil
func (o *Package) UnsetComment() {
	o.Comment.Unset()
}

func (o Package) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Package) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["packageId"] = o.PackageId
	toSerialize["size"] = o.Size
	toSerialize["hashes"] = o.Hashes
	if o.PkgType.IsSet() {
		toSerialize["pkgType"] = o.PkgType.Get()
	}
	if !IsNil(o.HardwareIds) {
		toSerialize["hardwareIds"] = o.HardwareIds
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if o.Uri.IsSet() {
		toSerialize["uri"] = o.Uri.Get()
	}
	if o.ProprietaryMeta.IsSet() {
		toSerialize["proprietaryMeta"] = o.ProprietaryMeta.Get()
	}
	if o.Comment.IsSet() {
		toSerialize["comment"] = o.Comment.Get()
	}
	return toSerialize, nil
}

func (o *Package) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
		"packageId",
		"size",
		"hashes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPackage := _Package{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPackage)

	if err != nil {
		return err
	}

	*o = Package(varPackage)

	return err
}

type NullablePackage struct {
	value *Package
	isSet bool
}

func (v NullablePackage) Get() *Package {
	return v.value
}

func (v *NullablePackage) Set(val *Package) {
	v.value = val
	v.isSet = true
}

func (v NullablePackage) IsSet() bool {
	return v.isSet
}

func (v *NullablePackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackage(val *Package) *NullablePackage {
	return &NullablePackage{value: val, isSet: true}
}

func (v NullablePackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


