/*
Torizon OTA

 This API is rate limited and will return the following headers for each API call.    - X-RateLimit-Limit - The total number of requests allowed within a time period   - X-RateLimit-Remaining - The total number of requests still allowed until the end of the rate limiting period   - X-RateLimit-Reset - The number of seconds until the limit is fully reset  In addition, if an API client is rate limited, it will receive a HTTP 420 response with the following header:     - Retry-After - The number of seconds to wait until this request is allowed  

API version: 2.0-Beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConflictRepr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConflictRepr{}

// ConflictRepr struct for ConflictRepr
type ConflictRepr struct {
	Msg string `json:"msg"`
	Description NullableString `json:"description,omitempty"`
	Code string `json:"code"`
	Cause NullableString `json:"cause,omitempty"`
	ErrorId NullableString `json:"errorId,omitempty"`
}

type _ConflictRepr ConflictRepr

// NewConflictRepr instantiates a new ConflictRepr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConflictRepr(msg string, code string) *ConflictRepr {
	this := ConflictRepr{}
	this.Msg = msg
	this.Code = code
	return &this
}

// NewConflictReprWithDefaults instantiates a new ConflictRepr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConflictReprWithDefaults() *ConflictRepr {
	this := ConflictRepr{}
	return &this
}

// GetMsg returns the Msg field value
func (o *ConflictRepr) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *ConflictRepr) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *ConflictRepr) SetMsg(v string) {
	o.Msg = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConflictRepr) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConflictRepr) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ConflictRepr) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ConflictRepr) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ConflictRepr) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ConflictRepr) UnsetDescription() {
	o.Description.Unset()
}

// GetCode returns the Code field value
func (o *ConflictRepr) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ConflictRepr) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ConflictRepr) SetCode(v string) {
	o.Code = v
}

// GetCause returns the Cause field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConflictRepr) GetCause() string {
	if o == nil || IsNil(o.Cause.Get()) {
		var ret string
		return ret
	}
	return *o.Cause.Get()
}

// GetCauseOk returns a tuple with the Cause field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConflictRepr) GetCauseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cause.Get(), o.Cause.IsSet()
}

// HasCause returns a boolean if a field has been set.
func (o *ConflictRepr) HasCause() bool {
	if o != nil && o.Cause.IsSet() {
		return true
	}

	return false
}

// SetCause gets a reference to the given NullableString and assigns it to the Cause field.
func (o *ConflictRepr) SetCause(v string) {
	o.Cause.Set(&v)
}
// SetCauseNil sets the value for Cause to be an explicit nil
func (o *ConflictRepr) SetCauseNil() {
	o.Cause.Set(nil)
}

// UnsetCause ensures that no value is present for Cause, not even an explicit nil
func (o *ConflictRepr) UnsetCause() {
	o.Cause.Unset()
}

// GetErrorId returns the ErrorId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConflictRepr) GetErrorId() string {
	if o == nil || IsNil(o.ErrorId.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorId.Get()
}

// GetErrorIdOk returns a tuple with the ErrorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConflictRepr) GetErrorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorId.Get(), o.ErrorId.IsSet()
}

// HasErrorId returns a boolean if a field has been set.
func (o *ConflictRepr) HasErrorId() bool {
	if o != nil && o.ErrorId.IsSet() {
		return true
	}

	return false
}

// SetErrorId gets a reference to the given NullableString and assigns it to the ErrorId field.
func (o *ConflictRepr) SetErrorId(v string) {
	o.ErrorId.Set(&v)
}
// SetErrorIdNil sets the value for ErrorId to be an explicit nil
func (o *ConflictRepr) SetErrorIdNil() {
	o.ErrorId.Set(nil)
}

// UnsetErrorId ensures that no value is present for ErrorId, not even an explicit nil
func (o *ConflictRepr) UnsetErrorId() {
	o.ErrorId.Unset()
}

func (o ConflictRepr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConflictRepr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msg"] = o.Msg
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["code"] = o.Code
	if o.Cause.IsSet() {
		toSerialize["cause"] = o.Cause.Get()
	}
	if o.ErrorId.IsSet() {
		toSerialize["errorId"] = o.ErrorId.Get()
	}
	return toSerialize, nil
}

func (o *ConflictRepr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msg",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConflictRepr := _ConflictRepr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConflictRepr)

	if err != nil {
		return err
	}

	*o = ConflictRepr(varConflictRepr)

	return err
}

type NullableConflictRepr struct {
	value *ConflictRepr
	isSet bool
}

func (v NullableConflictRepr) Get() *ConflictRepr {
	return v.value
}

func (v *NullableConflictRepr) Set(val *ConflictRepr) {
	v.value = val
	v.isSet = true
}

func (v NullableConflictRepr) IsSet() bool {
	return v.isSet
}

func (v *NullableConflictRepr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConflictRepr(val *ConflictRepr) *NullableConflictRepr {
	return &NullableConflictRepr{value: val, isSet: true}
}

func (v NullableConflictRepr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConflictRepr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


